### ISSUE TITLE
刚运行就报错

### ISSUE THREAD

**Issue by pricnehao** [aishang5wpj/RichEditText#2]
Activity com.xiaohongshu.richmodule.MainActivity has leaked IntentReceiver android.widget.EditText$1@41f3d940 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                            android.app.IntentReceiverLeaked: Activity com.xiaohongshu.richmodule.MainActivity has leaked IntentReceiver android.widget.EditText$1@41f3d940 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:796)
                                                                                at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:597)
                                                                                at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1446)
                                                                                at android.app.ContextImpl.registerReceiver(ContextImpl.java:1426)
                                                                                at android.app.ContextImpl.registerReceiver(ContextImpl.java:1420)
                                                                                at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:467)
                                                                                at android.widget.EditText.<init>(EditText.java:84)
                                                                                at com.xiaohongshu.richmodule.view.RichEdittext.<init>(RichEdittext.java:46)
                                                                                at com.xiaohongshu.richmodule.view.RichEdittext.<init>(RichEdittext.java:42)
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                at com.xiaohongshu.richmodule.MainActivity.onCreate(MainActivity.java:31)
                                                                                at android.app.Activity.performCreate(Activity.java:5303)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2242)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5132)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by aishang5wpj** [comment]
这个项目不要看了，看这个吧
https://github.com/aishang5wpj/RichEditTextPro
